<?php
include('./includes/antelope.inc');
$page_title = 'Spectrogram Mosaic';
$css = array( "css/style.css", "css/style2.css" );
$googlemaps = 0;
$js = array();

// Standard XHTML header
include('./includes/header.inc');

?>

<body bgcolor="#FFFFFF">
<script type="text/javascript">
<!--
    function toggle_visibility(id) {
       var e = document.getElementById(id);
       if(e.style.display == 'block')
          e.style.display = 'none';
       else
          e.style.display = 'block';
    }
//-->
</script>

<?php

	# global variables
	$debugging = 0;


	# header files
	include('./includes/daysPerMonth.inc');
	#include('./includes/mosaicMaker.inc');
	include('./includes/mosaicMakerTable.inc');
	include('./includes/findprevnextsubnets.inc');
	include('./includes/scriptname.inc');

	# Set date/time now
	$timenow = now();
	$currentYear = epoch2str($timenow, "%Y");
	$currentMonth = epoch2str($timenow, "%m");
	$currentDay = epoch2str($timenow, "%d");
	$currentHour = epoch2str($timenow, "%H");
#	$currentMinute = epoch2str($timenow, "%i);


	# Set convenience variables from CGI parameters
	$subnet = !isset($_REQUEST['subnet'])? $subnets[0] : $_REQUEST['subnet'];
	$plotsPerRow = !isset($_REQUEST['plotsPerRow'])? 6 : $_REQUEST['plotsPerRow'];
	if (isset($_REQUEST['starthour'])) {
		$starthour = $_REQUEST['starthour'];
        	$endhour = !isset($_REQUEST['endhour'])? 0 : $_REQUEST['endhour'];
                if ($starthour < $endhour) {
			$tmphour = $endhour;
			$endhour = $starthour;
			$starthour = $tmphour;
		} 
		$timestart = now() - $starthour * 3600;
        	list($year, $month, $day, $hour, $minute) = epoch2YmdHM($timestart);
        	$minute=floorminute($minute);
        	$numhours = $starthour - $endhour;
		$_REQUEST['year'] = $year;
		$_REQUEST['month'] = $month;
		$_REQUEST['day'] = $day;
		$_REQUEST['hour'] = $hour;
		$_REQUEST['minute'] = $minute;
		$_REQUEST['numhours'] = $numhours;
	} else {
		$year = !isset($_REQUEST['year'])? $currentYear : $_REQUEST['year'];
		$month = !isset($_REQUEST['month'])? $currentMonth : $_REQUEST['month'];
		$day = !isset($_REQUEST['day'])? $currentDay : $_REQUEST['day'];
		$hour = !isset($_REQUEST['hour'])? $currentHour : $_REQUEST['hour'];
		$minute = !isset($_REQUEST['minute'])? "00" : $_REQUEST['minute'];
		$numhours = !isset($_REQUEST['numhours'])? 2 : $_REQUEST['numhours'];
	}
		
	# Degugging
	if ($debugging == 1) {
		echo "<p>subnet=$subnet ";
		echo "year=$year ";
		echo "month=$month ";
		echo "day=$day ";
		echo "hour=$hour ";
		echo "minute=$minute ";
		echo "hour=$hour ";
		echo "numhours=$numhours ";
		echo "starthour=$starthour ";
		echo "endhour=$endhour <p>\n ";
		echo "<hr/>\n";
	}

	# Horizontal rule
	print "<hr />";

 
	if(isset($_REQUEST["subnet"])) {
		if (isset($_REQUEST["year"]) && isset($_REQUEST["month"]) && isset($_REQUEST["day"]) && isset($_REQUEST["hour"])  && isset($_REQUEST["numhours"])  ) {

			# make sure the date is valid
			if(!checkdate($month,$day,$year)){
				echo "<p>invalid date</p>";
 			}
			else
			{

				# generate the epoch time now
				$timenow   = time(); # seconds # get utc/local conversion issues
				$timenow = now();
	
				# generate the epoch time for the start date/time requested
				#$starttime = mktime($hour, $minute, 0, $month, $day, $year); # get local/utc conversion issues
				$starttime = str2epoch("$year/$month/$day $hour:$minute:00");
			#	echo "<p>Starttime: $starttime, timenow: $timenow</p>";	
				if ($timenow > $starttime) {
				
					# work out the difference in seconds
					$starthour = (($timenow - $starttime) / 3600);
					$endhour   = (($timenow - $starttime) / 3600) - $numhours;
					mosaicMaker($subnet, $starthour, $endhour, $plotsPerRow, $WEBPLOTS);
				}
				else
				{
					echo "<p>Date/Time entered must be in the past</p>\n";
				}
			}
		} 
	}
	else
	{
		echo "<h1>Welcome to the Spectrogram Mosaic Maker!</h1><p>This page provides links to pre-generated png files of 10-minute spectrograms generated by the \"TreMoR\" system.</p>";
	}

	# THE FORM
	echo "<hr />\n";
	echo "<table><tr><td>";

	# Start form
	echo "<form method=\"get\"> ";

	# Start table
	echo "<table>\n\n";

	# Subnet widgit
	echo "<tr><td>Subnet</td>\n";
	echo "<td><select name=\"subnet\"> ";
	echo "<option value=\"$subnet\" SELECTED>$subnet</option>";
	foreach ($subnets as $subnet_option) {
		print "<option value=\"$subnet_option\">$subnet_option</option> ";
	}
	print "</select>";
	echo "</td></tr>\n";
?>

<?php
        # Start hour widgit
        echo "<tr><td>Start</td>\n";
        printf("<td><input type=\"text\" name=\"starthour\" value=\"%.0f\" size=\"4\"> ",$starthour);
        echo " hours ago </td>\n";

        # End hour widgit
        echo "<td>End</td>\n";
        printf("<td><input type=\"text\" name=\"endhour\" value=\"%.0f\" size=\"4\"> ",$endhour);
        echo " hours ago</td>\n";

        # End hour widgit
        echo "<td>Spectrograms per row:</td>\n";
        printf("<td><input type=\"text\" name=\"plotsPerRow\" value=\"%.0f\" size=\"4\"> ",$plotsPerRow);
        echo " </tr>\n";
?>
	</div>

<?php
	################## START TIME
	echo "<tr><td>Start time (UTC):</td><td>\n";
	# start new table inside this cell
	echo "<table><tr>\n";

	# Year widgit
	echo "<td>Year:</td>\n";
	echo "<td><input type=\"text\" name=\"year\" value=\"$year\" size=\"4\" readonly=readonly> ";
	echo "</td>\n";

	# Month widgit
	echo "<td>Month:</td>\n";
	echo "<td><input type=\"text\" name=\"month\" value=\"$month\" size=\"2\" readonly=readonly> ";
	echo "</td>\n";

	# Day widgit
	echo "<td>Day:</td>\n";
	echo "<td><input type=\"text\" name=\"day\" value=\"$day\" size=\"2\" readonly=readonly> ";
	echo "</td>\n";

	# Hour widgit
	echo "<td>Hour:</td>\n";
	echo "<td><input type=\"text\" name=\"hour\" value=\"$hour\" size=\"2\" readonly=readonly > ";
	echo "</td>\n";

	# Minute widgit
	echo "<td>Minute:</td>\n";
	echo "<td><select name=\"minute\" disabled=disabled> ";
	echo "<option value=\"$minute\" SELECTED>$minute</option>";
	$minutes = array("00", "10", "20", "30", "40", "50");
	foreach ($minutes as $minute_option) {
		print "<option value=\"$minute_option\">$minute_option</option> ";
	}
	print "</select>";
	echo "</td>\n";

	# end this table
	echo "</tr></table>\n";

	# end this cell and row
	echo "</td></tr>\n";
	###################### END OF START TIME

	# Number of hours widgit
	echo "<tr><td>Number of hours:</td>\n";
	echo "<td><input type=\"text\" name=\"numhours\" value=\"$numhours\" size=\"2\" readonly=readonly> ";
	echo "</td></tr>\n";

?>
	</div>
<?php

	# Submit & Reset buttons
	echo "<tr>\n";
	print "<td><input type=\"submit\" name=\"submit\" value=\"Make Mosaic\"></td>\n";

	echo "</tr>\n";

	# End the table
	echo "</table>\n";
?>


<?php
	# End form
	echo "</form>\n";



	# Add mosaic arrows
	$scriptname = scriptname();
	if ($debugging == 1) {
        	echo "scriptname = $scriptname, subnet=$subnet, $year/$month/$day $hour:$minute:00, previous=$previousSubnet, next=$nextSubnet\n";
	}

        list ($previousSubnet, $nextSubnet) = findprevnextsubnets($subnet, $subnets);
        $numseconds = $numhours * 3600;
        list ($pyear, $pmonth, $pday, $phour, $pminute, $psecs) = addSeconds($year, $month, $day, $hour, $minute, 0, -$numseconds);
        $pminute=floorminute($pminute);

        list ($nyear, $nmonth, $nday, $nhour, $nminute, $nsecs) = addSeconds($year, $month, $day, $hour, $minute, 0, $numseconds);
        $nminute=floorminute($nminute);

        echo "</td><td>\n";

        # diagnostic info
        echo "</td><td>\n";

                echo "<table><tr><td>\n";
                echo "&nbsp;\n";
                echo "</td><td>\n";
                echo "<a href=\"$scriptname?subnet=$previousSubnet&year=$year&month=$month&day=$day&hour=$hour&minute=$minute&numhours=$numhours\"><img height=50 width=50 src=images/uparrow.gif></a>\n";
                echo "</td><td>\n";
                echo "&nbsp;\n";
                echo "</td></tr>\n";

                echo "<tr><td>\n";
                echo "<a href=\"$scriptname?subnet=$subnet&year=$pyear&month=$pmonth&day=$pday&hour=$phour&minute=$pminute&numhours=$numhours\"><img height=50 width=50 src=images/leftarrow.gif></a>\n";
                echo "</td><td align=center>\n";
                echo "<a href=\"$scriptname?subnet=$subnet&starthour=$numhours&endhour=0\">Now</a>\n";
                echo "</td><td>\n";
                echo "<a href=\"$scriptname?subnet=$subnet&year=$nyear&month=$nmonth&day=$nday&hour=$nhour&minute=$nminute&numhours=$numhours\"><img height=50 width=50 src=images/rightarrow.gif></a>\n";
                echo "</td></tr>\n";

                echo "<tr><td>\n";
                echo "&nbsp;\n";
                echo "</td><td>\n";
                echo "<a href=\"$scriptname?subnet=$nextSubnet&year=$year&month=$month&day=$day&hour=$hour&minute=$minute&numhours=$numhours\"><img height=50 width=50 src=images/downarrow.gif></a>\n";
                echo "</td><td>\n";
                echo "&nbsp;\n";
                echo "</td></tr></table>\n";

        echo "</td></tr></table>\n";

?>


<div><script language="Javascript" type="text/javascript">now = new Date;document.write("<p>Generated: " + now.toUTCString()  + "</p>");</script></div>

</body>
</html>
